### ISSUE TITLE
Critical: FO-stylesheets (suse2013) produce faulty .fo file

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/suse-xsl#97]
The attached fo file (named *.txt, otherwise GitHub does not allow an upload) produces the following error when being processed with FOP. (XEP works fine)

```
15:11 $ fop table_missing_child_elements_error.fo foo.pdf
Nov 16, 2015 3:12:05 PM org.apache.fop.apps.FopFactoryConfigurator configure
INFO: Default page-height set to: 11in
Nov 16, 2015 3:12:05 PM org.apache.fop.apps.FopFactoryConfigurator configure
INFO: Default page-width set to: 8.26in
Nov 16, 2015 3:12:06 PM org.apache.fop.apps.FOUserAgent processEvent
WARNING: Only a value of "auto" for block-progression-dimension has a well-specified behavior on fo:table. Falling back to "auto". (See position 1232:9)
Nov 16, 2015 3:12:06 PM org.apache.fop.cli.InputHandler error
SEVERE: javax.xml.transform.TransformerException: file:/data/git/doc-ses/en/build/.tmp/table_missing_child_elements_error.fo:1235:43: "fo:table-cell" is missing child elements. Required content model: marker* (%block;)+ (See position 1235:43)
Nov 16, 2015 3:12:06 PM FOP startFOP
SEVERE: Exception
org.apache.fop.apps.FOPException: org.apache.fop.fo.ValidationException: "fo:table-cell" is missing child elements. Required content model: marker* (%block;)+ (See position 1235:43)
javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: "fo:table-cell" is missing child elements. Required content model: marker* (%block;)+ (See position 1235:43)
	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:303)
	at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:130)
	at org.apache.fop.cli.Main.startFOP(Main.java:177)
	at org.apache.fop.cli.Main.main(Main.java:207)
Caused by: javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: "fo:table-cell" is missing child elements. Required content model: marker* (%block;)+ (See position 1235:43)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:749)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:351)
	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:300)
	... 3 more
Caused by: org.apache.fop.fo.ValidationException: "fo:table-cell" is missing child elements. Required content model: marker* (%block;)+ (See position 1235:43)
```

[table_missing_child_elements_error.txt](https://github.com/openSUSE/suse-xsl/files/35564/table_missing_child_elements_error.txt)

**Comment by sknorr** [comment]
This is from the SES Guide from develop. This only happens with the DB5 (-ns) stylesheets.
